"""sample comment

Revision ID: 35884b649e79
Revises: 
Create Date: 2024-01-23 16:15:18.677607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35884b649e79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('hehe', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'hehe')
    # ### end Alembic commands ###
