"""First commit

Revision ID: 352d4c3884db
Revises: 7c7b8d1719b7
Create Date: 2024-01-23 16:25:27.286964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352d4c3884db'
down_revision = '7c7b8d1719b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('ausdfthor', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'ausdfthor')
    # ### end Alembic commands ###
