"""First commit

Revision ID: 7c7b8d1719b7
Revises: 35884b649e79
Create Date: 2024-01-23 16:24:43.321981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7b8d1719b7'
down_revision = '35884b649e79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
