"""First commit

Revision ID: ba7fbaae764c
Revises: 352d4c3884db
Create Date: 2024-01-23 16:26:18.619051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7fbaae764c'
down_revision = '352d4c3884db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('ausdfthor', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'ausdfthor')
    # ### end Alembic commands ###
